/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package btctracer;

public class App {
   

    public static void main(String[] args) {
        Search s = new Search("bc1qtyr35207fd5djffwjqgllqyld7yjzv8jvm77rk");
    }
}
