/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package btctracer;

import java.io.File;
import java.io.IOException;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {

  public static void main(String[] args) {
   
    //Handler h = new Handler("bc1qyquuwt57xjteqs7feglsvgfq8qcpdv5cmzt9kv",2);
    //System.out.print(Handler.output);
    launch(args);
  }

  @Override
  public void start(Stage primaryStage) throws Exception {
    primaryStage.setTitle("BTC Investigator");
    try {
      File file = new File("src/main/resources/GUI.fxml");
      Parent root = FXMLLoader.load(file.toURI().toURL());
      Scene scene = new Scene(root);
      primaryStage.setScene(scene);
      primaryStage.show();
    } catch (IOException e) {
      e.printStackTrace();
    }

  }
}
